"""Link-mode adapter: collect tile sources and emit the declarations header."""
from __future__ import annotations

from ..ir.types import Graph


def collect_sources(graph: Graph) -> list[str]:
    seen: list[str] = []
    for g in graph.grids:
        if g.body.kind in ("hip_link", "cuda_link") and g.body.source and g.body.source not in seen:
            seen.append(g.body.source)
    return seen


def emit_tile_decls(graph: Graph) -> str:
    out = ["// generated by etx: tile body prototypes (link mode)", "#pragma once", "#include \"etx/abi.h\"", ""]
    for g in graph.grids:
        if g.body.kind in ("hip_link", "cuda_link", "builtin"):
            out.append(f"extern \"C\" __device__ void {g.body.symbol}(const etx_ctx* ctx);   // grid {g.name} {g.grid}")
    out.append("")
    return "\n".join(out)
