"""Host-DSL mode: emit a Triton persistent-kernel skeleton for a plan.

Triton cannot export linkable device functions, but @triton.jit functions can
call each other, so the persistent loop itself is generated in Triton and the
tile bodies are jit functions.  Runtime primitives map to tl.atomic_* ; the
backoff and the AMD cache-scope bits need tl.inline_asm_elementwise (the AMD
backend exposes no s_sleep / s_setprio hooks).  This emitter produces the
skeleton with the dispatch table filled in; edge-map loops are emitted as
Triton scalar loops.  Status: skeleton, not yet executed.
"""
from __future__ import annotations

from ..passes.plan import Plan


def emit_triton_skeleton(plan: Plan) -> str:
    grids = plan.graph.grids
    modules = sorted({g.body.source for g in grids if g.body.kind == "triton" and g.body.source})
    out = ["# generated by etx: Triton host-DSL persistent kernel skeleton",
           "import triton", "import triton.language as tl", ""]
    for mod in modules:
        out.append(f"from {mod} import *  # tile bodies")
    out += ["", "@triton.jit",
            "def _etx_wait(ev_ptr, idx):",
            "    while tl.atomic_add(ev_ptr + idx, 0, sem='acquire') > 0:",
            "        pass  # TODO backoff via tl.inline_asm_elementwise (s_sleep / nanosleep)",
            "",
            "@triton.jit",
            "def _etx_arrive(ev_ptr, idx):",
            "    return tl.atomic_add(ev_ptr + idx, -1, sem='release') - 1",
            "",
            "@triton.jit",
            "def etx_megakernel(shape_ptr, events_ptr, descs_ptr, static_queue_ptr, static_begin_ptr, static_end_ptr,",
            "                   local_head_ptr, local_tail_ptr, local_slots_ptr, ctrl_done_ptr, n_tasks: tl.constexpr,",
            "                   *args):",
            "    worker = tl.program_id(0)",
            "    cursor = tl.load(static_begin_ptr + worker)",
            "    cend = tl.load(static_end_ptr + worker)",
            "    while cursor < cend:",
            "        tid = tl.load(static_queue_ptr + cursor)",
            "        ttype = tl.load(descs_ptr + tid * 5)",
            "        c0 = tl.load(descs_ptr + tid * 5 + 1)",
            "        c1 = tl.load(descs_ptr + tid * 5 + 2)"]
    for g in grids:
        tid_ = plan.type_ids[g.name]
        out.append(f"        if ttype == {tid_}:  # {g.name} [{plan.modes.get(g.name)}]")
        for ev, m in g.in_edges.items():
            ep = plan.events[ev]
            out.append(f"            # wait {ev} via {m.text!r}: targets enumerated per edge map, offset {ep.offset}")
        out.append(f"            {g.body.symbol}(c0, c1, shape_ptr, *args)")
        for ev, m in g.out_edges.items():
            ep = plan.events[ev]
            out.append(f"            # arrive {ev} via {m.text!r}, offset {ep.offset}")
    out += ["        cursor += 1",
            "        tl.atomic_add(ctrl_done_ptr, 1)",
            ""]
    return "\n".join(out)
