"""Persistent-kernel emitter (L5).

Emits one translation unit per kernel instance:
  * a dispatch switch over task types calling the frontend-provided tile bodies
  * per-type wait code generated from the in-edge maps (targets enumerated in C)
  * per-type arrive code from the out-edge maps, with pushes for dynamic events
  * the worker loop: static head if ready -> pop local/global -> spin on head
HIP and CUDA share the template; every hardware-specific line comes from
etx_lowering.h.  The plan (queues, descriptors, event layout, consumer lists)
is emitted separately as JSON for the host launcher.
"""
from __future__ import annotations

import json
from typing import Any

from ..ir.types import Scope, TaskGrid
from ..passes.plan import Plan


def _scope_macro(plan: Plan, event: str) -> str:
    return plan.events[event].scope.name


def _runtime_ptrs(plan: Plan, g: TaskGrid) -> dict[str, str]:
    ptrs = {}
    for m in list(g.in_edges.values()) + list(g.out_edges.values()):
        for rt in m.runtime:
            ptrs[rt] = f"((const int32_t*)p.args[{_arg_index(plan, rt)}])"
    return ptrs


_ARG_CACHE: dict[int, dict[str, int]] = {}


def _arg_table(plan: Plan) -> dict[str, int]:
    key = id(plan)
    if key not in _ARG_CACHE:
        names: list[str] = []
        for t in plan.graph.tensors:
            names.append(t)
        _ARG_CACHE[key] = {n: i for i, n in enumerate(names)}
    return _ARG_CACHE[key]


def _arg_index(plan: Plan, tensor: str) -> int:
    return _arg_table(plan)[tensor]


def _gather_width(plan: Plan, tensor: str) -> str:
    t = plan.graph.tensors[tensor]
    if len(t.shape) >= 2:
        return f"p.shape[{plan.graph.symbols.index(t.shape[1])}]" if isinstance(t.shape[1], str) and t.shape[1] in plan.graph.symbols else str(t.shape[1])
    return "1"


def _symbols(plan: Plan) -> dict[str, str]:
    return {s: f"p.shape[{i}]" for i, s in enumerate(plan.graph.symbols)}


def _wait_code(plan: Plan, g: TaskGrid) -> str:
    lines = []
    coord_vars = [f"t.coord[{i}]" for i in range(len(g.grid))]
    for ev, m in g.in_edges.items():
        ep = plan.events[ev]
        sc = ep.scope.name
        width = _gather_width(plan, m.gather_tensor) if m.kind == "gather" else ""
        lines.append(f"      // wait {ev} via {m.text!r} ({sc})")
        lines.append(f"#define ETX_TARGET(idx) etx_wait_{sc}(p.events + {ep.offset} + (idx))")
        lines.append(m.to_c(coord_vars, f"p.ev_shape[{list(plan.events).index(ev)}]", "ETX_TARGET",
                            _runtime_ptrs(plan, g), width, _symbols(plan)).rstrip())
        lines.append("#undef ETX_TARGET")
    return "\n".join(lines)


def _arrive_code(plan: Plan, g: TaskGrid, mode: str) -> str:
    lines = []
    coord_vars = [f"t.coord[{i}]" for i in range(len(g.grid))]
    for ev, m in g.out_edges.items():
        ep = plan.events[ev]
        sc = ep.scope.name
        ev_id = list(plan.events).index(ev)
        width = _gather_width(plan, m.gather_tensor) if m.kind == "gather" else ""
        lines.append(f"      // arrive {ev} via {m.text!r} ({sc})")
        if mode == "static":
            lines.append(f"#define ETX_TARGET(idx) (void)etx_arrive_{sc}(p.events + {ep.offset} + (idx))")
        else:
            lines.append(f"#define ETX_TARGET(idx) do {{ if (etx_arrive_{sc}(p.events + {ep.offset} + (idx)) == 0) etx_push_consumers(p, {ev_id}, (idx), worker); }} while (0)")
        lines.append(m.to_c(coord_vars, f"p.ev_shape[{ev_id}]", "ETX_TARGET", _runtime_ptrs(plan, g), width, _symbols(plan)).rstrip())
        lines.append("#undef ETX_TARGET")
    return "\n".join(lines)


def emit_kernel(plan: Plan, device: int = 0) -> str:
    m = plan.machine
    is_hip = m.vendor == "amd"
    grids = [g for g in plan.graph.grids if g.device == device]
    threads = max([g.resource.threads for g in grids] + [64])
    lds = max([g.resource.lds_bytes + g.resource.prefetch_bytes for g in grids] + [0])
    out: list[str] = []
    out.append(f"// generated by etx: graph {plan.graph.name}, arch {m.name}, device {device}")
    out.append("// tile bodies are linked from the frontend (link mode); this file owns the persistent loop only")
    out.append("#include \"etx/abi.h\"")
    out.append("#include \"etx_lowering.h\"")
    out.append("#include \"etx/primitives.h\"")
    out.append("")
    for g in grids:
        out.append(f"extern \"C\" __device__ void {g.body.symbol}(const etx_ctx*);")
        for pro in g.prologue:
            out.append(f"// {g.name}: prologue recomputes {pro} (event eliminated by Pass 3)")
    out.append("")
    out.append(f"#define ETX_THREADS {threads}")
    out.append(f"#define ETX_LDS_USED {lds}")
    out.append("")
    out.append("static __device__ __forceinline__ void etx_run_task(const etx_params& p, const etx_task t, uint32_t worker, uint32_t domain) {")
    out.append("  __shared__ __align__(16) unsigned char etx_lds[ETX_LDS_USED > 0 ? ETX_LDS_USED : 16];")
    out.append("  etx_ctx ctx; for (int i = 0; i < 4; ++i) ctx.coord[i] = t.coord[i];")
    out.append("  ctx.shape = p.shape; ctx.args = p.args; ctx.events = p.events; ctx.ev_offset = p.ev_offset; ctx.ev_shape = (const int32_t*)p.ev_shape;")
    out.append("  ctx.domain = domain; ctx.worker = worker; ctx.lds = etx_lds;")
    out.append("  switch (t.type) {")
    for g in grids:
        mode = plan.modes.get(g.name, "static")
        out.append(f"    case {plan.type_ids[g.name]}: {{ // {g.name} [{mode}] grid={g.grid}")
        out.append("      if (threadIdx.x == 0) {")
        out.append(_wait_code(plan, g))
        out.append("      }")
        out.append("      __syncthreads();")
        for ev in g.in_edges:
            out.append(f"      ETX_ACQUIRE_{_scope_macro(plan, ev)}();")
        out.append(f"      {g.body.symbol}(&ctx);")
        out.append("      __syncthreads();")
        out.append("      if (threadIdx.x == 0) {")
        for ev in g.out_edges:
            out.append(f"        ETX_RELEASE_{_scope_macro(plan, ev)}();")
        out.append(_arrive_code(plan, g, mode))
        out.append("      }")
        out.append("      break; }")
    out.append("    default: break;")
    out.append("  }")
    out.append("}")
    out.append("")
    out.append("extern \"C\" __global__ void __launch_bounds__(ETX_THREADS) etx_megakernel(etx_params p) {")
    out.append("  const uint32_t worker = blockIdx.x;")
    out.append("  __shared__ uint32_t s_domain; __shared__ int32_t s_tid;")
    out.append("  if (threadIdx.x == 0) { s_domain = etx_discover_domain(p, worker); }")
    out.append("  __syncthreads();")
    out.append("  const uint32_t domain = s_domain;")
    out.append("  int32_t cursor = p.static_begin[worker]; const int32_t cend = p.static_end[worker];")
    out.append("  uint32_t spins = 0;")
    out.append("  for (;;) {")
    out.append("    if (threadIdx.x == 0) {")
    out.append("      int32_t tid = -1;")
    out.append("      if (cursor < cend) { int32_t h = p.static_queue[cursor]; if (etx_deps_ready(p, h)) { tid = h; ++cursor; } }")
    out.append("      if (tid < 0) tid = etx_pop(p.local_queue + domain);")
    out.append("      if (tid < 0 && p.global_queue.capacity) tid = etx_pop(&p.global_queue);")
    out.append("      if (tid < 0 && cursor < cend) { tid = p.static_queue[cursor]; ++cursor; }   // spin on the head inside the wait code")
    out.append("      s_tid = tid;")
    out.append("    }")
    out.append("    __syncthreads();")
    out.append("    const int32_t tid = s_tid;")
    out.append("    if (tid < 0) {")
    out.append("      if (*p.ctrl_abort) break;")
    out.append("      if (etx_step_done(p)) break;")
    out.append("      ETX_BACKOFF(); if (++spins > p.spin_limit) { if (threadIdx.x == 0) atomicOr(p.ctrl_abort, 2); break; }")
    out.append("      __syncthreads(); continue;")
    out.append("    }")
    out.append("    spins = 0;")
    out.append("    etx_run_task(p, p.descs[tid], worker, domain);")
    out.append("    if (threadIdx.x == 0) atomicAdd(p.ctrl_done, 1);")
    out.append("    __syncthreads();")
    out.append("  }")
    out.append("}")
    out.append("")
    return "\n".join(out)


def emit_plan_json(plan: Plan) -> str:
    args = _arg_table(plan)
    data: dict[str, Any] = {
        "graph": plan.graph.name, "arch": plan.arch, "bindings": plan.bindings,
        "symbols": plan.graph.symbols, "shape": [plan.bindings.get(s) for s in plan.graph.symbols],
        "devices": plan.n_devices, "domains": plan.n_domains, "workers_per_domain": plan.workers_per_domain,
        "threads": max([g.resource.threads for g in plan.graph.grids] + [64]),
        "args": args,
        "types": {g.name: {"id": plan.type_ids[g.name], "symbol": g.body.symbol, "mode": plan.modes.get(g.name),
                           "grid": list(plan.inst.grid_shapes[g.name]), "prologue": g.prologue, "device": g.device}
                  for g in plan.graph.grids},
        "events": [{"name": e.name, "id": i, "offset": e.offset, "shape": list(e.shape), "scope": e.scope.name,
                    "memory": e.memory, "counts": e.counts, "runtime_init": e.runtime_init}
                   for i, e in enumerate(plan.events.values())],
        "descs": [{"id": t.id, "type": t.type_id, "coord": list(t.coord), "device": t.device, "domain": t.domain,
                   "worker": t.worker, "mode": t.mode} for t in plan.tasks],
        "static_queues": {f"{d}:{w}": q for (d, w), q in plan.static_queues.items()},
        "local_queue_capacity": {f"{d}:{dom}": c for (d, dom), c in plan.local_queue_capacity.items()},
        "global_queue_capacity": plan.global_queue_capacity,
        "ev_consumers": {f"{ev}:{lin}": ids for (ev, lin), ids in plan.ev_consumers.items()},
        "tensor_placement": plan.tensor_placement,
        "prefetch": plan.prefetch,
        "eliminated_events": plan.eliminated_events,
        "kernel_instances": plan.kernel_instances,
        "log": plan.log,
    }
    return json.dumps(data, indent=1)
