"""Primitive x architecture lowering table -> etx_lowering.h.

Every macro comes from the machine YAML's visibility / lowering entries.  The
kernel emitter never spells an instruction; it only picks a scope.
"""
from __future__ import annotations

from ..ir.types import Scope
from ..machine.model import MachineModel

SCOPES = [Scope.DOMAIN, Scope.DEVICE, Scope.SYSTEM]


def emit_lowering_header(m: MachineModel) -> str:
    out = [f"// generated by etx for {m.name} ({m.family}); do not edit",
           "#pragma once",
           f"#define ETX_ARCH \"{m.name}\"",
           f"#define ETX_VENDOR_{m.vendor.upper()} 1",
           f"#define ETX_WAVE_SIZE {m.wave_size}",
           f"#define ETX_NUM_DOMAINS {m.num_domains}",
           f"#define ETX_CUS_PER_DOMAIN {m.cus_per_domain()}",
           f"#define ETX_LDS_BYTES {int(m.resources['lds_kb']) * 1024}",
           f"#define ETX_BACKOFF() do {{ {m.lowering.get('backoff', '')} }} while (0)",
           f"#define ETX_TIMER() ({m.lowering.get('timer', '0')})",
           f"#define ETX_DOMAIN_ID() ({m.lowering.get('domain_id', '0')})",
           ""]
    for s in SCOPES:
        v = m.vis(s)
        eff = m.effective_scope(s)
        name = s.name
        rel = " ".join(v.release) or "/* none */;"
        acq = " ".join(v.acquire) or "/* none */;"
        out.append(f"// scope {name} lowers to {eff.name} on {m.name} (memory: {v.memory})")
        out.append(f"#define ETX_RELEASE_{name}() do {{ {rel} }} while (0)")
        out.append(f"#define ETX_ACQUIRE_{name}() do {{ {acq} }} while (0)")
        out.append(f"#define ETX_POLL_{name}(ptr) ({v.poll.format(ptr='(ptr)')})")
        out.append(f"#define ETX_ARRIVE_{name}(ptr) ({v.arrive.format(ptr='(ptr)')})")
        out.append("")
    for k, val in sorted(m.capabilities.items()):
        if isinstance(val, bool):
            out.append(f"#define ETX_CAP_{k.upper()} {int(val)}")
        else:
            out.append(f"#define ETX_CAP_{k.upper()}_{str(val).upper()} 1")
    out.append("")
    return "\n".join(out)
