"""plan_data.h: the Plan as constant C arrays for the host launcher.

Everything the host needs to run one step: shape scalars, descriptors,
static queues, event layout and initial counts, queue capacities, push lists
(CSR), tensor sizes.  Static arrays keep the first bring-up free of a JSON
parser; the production host reads plan.json instead.
"""
from __future__ import annotations

from ..passes.plan import Plan
from .kernel import _arg_table

ROLE_ID = {"activation": 0, "weight": 1, "runtime": 2, "scratch": 3, "recomputed": 3}


def emit_plan_header(plan: Plan, device: int = 0) -> str:
    g = plan.graph
    args = _arg_table(plan)
    out = ["// generated by etx: plan data for the host launcher", "#pragma once", "#include \"etx/abi.h\"", ""]
    out.append(f"#define ETX_N_SYMBOLS {len(g.symbols)}")
    shape = [plan.bindings.get(s, 0) for s in g.symbols]
    out.append(f"static const int32_t etx_shape[{max(1, len(shape))}] = {{{', '.join(map(str, shape)) or '0'}}};")
    out.append(f"#define ETX_N_TASKS {len(plan.tasks)}")
    out.append(f"#define ETX_N_DOMAINS {plan.n_domains}")
    out.append(f"#define ETX_WORKERS_PER_DOMAIN {plan.workers_per_domain}")
    out.append(f"#define ETX_N_WORKERS {plan.workers_per_device()}")
    out.append(f"#define ETX_THREADS {max([gg.resource.threads for gg in g.grids] + [64])}")
    # descriptors
    descs = []
    for t in plan.tasks:
        c = list(t.coord) + [0] * (4 - len(t.coord))
        descs.append(f"{{{t.type_id}, {{{c[0]}, {c[1]}, {c[2]}, {c[3]}}}}}")
    out.append(f"static const etx_task etx_descs[ETX_N_TASKS] = {{{', '.join(descs)}}};")
    # static queues
    sq, begin, end = [], [], []
    for w in range(plan.workers_per_device()):
        q = plan.static_queues.get((device, w), [])
        begin.append(len(sq))
        sq.extend(q)
        end.append(len(sq))
    out.append(f"#define ETX_STATIC_LEN {max(1, len(sq))}")
    out.append(f"static const int32_t etx_static_queue[ETX_STATIC_LEN] = {{{', '.join(map(str, sq)) or '0'}}};")
    out.append(f"static const int32_t etx_static_begin[ETX_N_WORKERS] = {{{', '.join(map(str, begin))}}};")
    out.append(f"static const int32_t etx_static_end[ETX_N_WORKERS] = {{{', '.join(map(str, end))}}};")
    # events
    evs = list(plan.events.values())
    out.append(f"#define ETX_N_EVENTS {len(evs)}")
    total_words = sum(e.numel for e in evs)
    out.append(f"#define ETX_EVENT_WORDS {max(1, total_words)}")
    out.append(f"static const int32_t etx_ev_offset[{max(1, len(evs))}] = {{{', '.join(str(e.offset) for e in evs) or '0'}}};")
    shapes = []
    for e in evs:
        s = list(e.shape) + [0] * (4 - len(e.shape))
        shapes.append(f"{{{s[0]}, {s[1]}, {s[2]}, {s[3]}}}")
    out.append(f"static const int32_t etx_ev_shape[{max(1, len(evs))}][4] = {{{', '.join(shapes) or '{0,0,0,0}'}}};")
    counts = []
    for e in evs:
        counts.extend(e.counts)
    out.append(f"static const int32_t etx_ev_counts[ETX_EVENT_WORDS] = {{{', '.join(map(str, counts)) or '0'}}};")
    out.append(f"static const int32_t etx_ev_runtime_init[{max(1, len(evs))}] = {{{', '.join('1' if e.runtime_init else '0' for e in evs) or '0'}}};")
    # queues
    caps = [plan.local_queue_capacity.get((device, d), 0) for d in range(plan.n_domains)]
    out.append(f"static const int32_t etx_local_capacity[ETX_N_DOMAINS] = {{{', '.join(map(str, caps))}}};")
    out.append(f"#define ETX_GLOBAL_CAPACITY {plan.global_queue_capacity.get(device, 0)}")
    # push lists CSR: per event a block of numel+1 offsets
    push_index, offsets, lists = [], [], []
    for e_id, e in enumerate(evs):
        push_index.append(len(offsets))
        for lin in range(e.numel):
            offsets.append(len(lists))
            for tid in plan.ev_consumers.get((e.name, lin), []):
                lists.append(tid if plan.tasks[tid].mode == "hybrid" else ~tid)
        offsets.append(len(lists))
    out.append(f"static const int32_t etx_push_index[{max(1, len(push_index))}] = {{{', '.join(map(str, push_index)) or '0'}}};")
    out.append(f"static const int32_t etx_push_offsets[{max(1, len(offsets))}] = {{{', '.join(map(str, offsets)) or '0'}}};")
    out.append(f"static const int32_t etx_push_lists[{max(1, len(lists))}] = {{{', '.join(map(str, lists)) or '0'}}};")
    # initially ready dynamic / hybrid tasks: seeded into the rings by the host at step start
    inst = plan.inst
    init_local: list[list[int]] = [[] for _ in range(plan.n_domains)]
    init_global: list[int] = []
    for t in plan.tasks:
        if t.mode == "static" or t.device != device:
            continue
        prods = {plan.task_index[p] for e in inst.task_in[(t.grid, t.coord)] for p in inst.producers[e]}
        if t.mode == "hybrid":
            local_prods = [p for p in prods if plan.tasks[p].domain == t.domain and plan.tasks[p].device == t.device]
            if not local_prods:
                init_local[t.domain].append(t.id)
        elif not prods:
            init_global.append(t.id)
    flat = [tid for d in init_local for tid in d]
    lens = [len(d) for d in init_local]
    out.append(f"static const int32_t etx_init_local[{max(1, len(flat))}] = {{{', '.join(map(str, flat)) or '0'}}};")
    out.append(f"static const int32_t etx_init_local_len[ETX_N_DOMAINS] = {{{', '.join(map(str, lens))}}};")
    out.append(f"static const int32_t etx_init_global[{max(1, len(init_global))}] = {{{', '.join(map(str, init_global)) or '0'}}};")
    out.append(f"#define ETX_INIT_GLOBAL_LEN {len(init_global)}")
    # tensors
    names = [n for n, _ in sorted(args.items(), key=lambda kv: kv[1])]
    out.append(f"#define ETX_N_ARGS {len(names)}")
    out.append("static const char* const etx_arg_names[ETX_N_ARGS] = {" + ", ".join(f'"{n}"' for n in names) + "};")
    out.append("static const size_t etx_arg_bytes[ETX_N_ARGS] = {" + ", ".join(str(g.tensors[n].nbytes(plan.bindings)) for n in names) + "};")
    out.append("static const int32_t etx_arg_role[ETX_N_ARGS] = {" + ", ".join(str(ROLE_ID.get(g.tensors[n].role, 0)) for n in names) + "};")
    # per task type: global arg indices in the grid's own argument order (-1 = unused slot)
    n_types = len(plan.type_ids)
    max_args = max([len(gg.args) for gg in g.grids] + [1])
    rows = []
    by_type = {plan.type_ids[gg.name]: gg for gg in g.grids}
    for t in range(n_types):
        gg = by_type.get(t)
        idx = [args[a] for a in gg.args] if gg else []
        idx += [-1] * (max_args - len(idx))
        rows.append("{" + ", ".join(map(str, idx)) + "}")
    out.append(f"#define ETX_N_TYPES {n_types}")
    out.append(f"#define ETX_MAX_ARGS {max_args}")
    out.append(f"static const int32_t etx_type_arg_index[ETX_N_TYPES][ETX_MAX_ARGS] = {{{', '.join(rows)}}};")
    out.append("")
    return "\n".join(out)
