"""plan_data.h: the Plan as constant C arrays for the host launcher, all devices.

Everything the host needs to run one step on every device: shape scalars,
descriptors (global task ids), per-device static queues, event layout and
initial counts (shared buffer), per-device queue capacities and initial ready
lists, push lists (CSR), per-type argument tables, tensor sizes.  Static arrays
keep the first bring-up free of a JSON parser; the production host reads
plan.json instead.
"""
from __future__ import annotations

from ..ir.types import Scope
from ..passes.plan import Plan
from .kernel import _arg_table

ROLE_ID = {"activation": 0, "weight": 1, "runtime": 2, "scratch": 3, "recomputed": 3}


def _arr(name: str, values: list, ctype: str = "int32_t", dims: str | None = None) -> str:
    n = max(1, len(values))
    body = ", ".join(map(str, values)) or "0"
    return f"static const {ctype} {name}[{dims or n}] = {{{body}}};"


def emit_plan_header(plan: Plan, device: int = 0) -> str:
    g = plan.graph
    args = _arg_table(plan)
    nd, ndom, wpd = plan.n_devices, plan.n_domains, plan.workers_per_domain
    nw = plan.workers_per_device()
    inst = plan.inst
    out = ["// generated by etx: plan data for the host launcher (all devices)", "#pragma once", "#include \"etx/abi.h\"", ""]
    shape = [plan.bindings.get(s, 0) for s in g.symbols]
    out.append(f"#define ETX_N_SYMBOLS {len(g.symbols)}")
    for i, s in enumerate(g.symbols):
        out.append(f"#define ETX_SYM_{s} {i}")
    out.append(_arr("etx_shape", shape))
    out.append(f"#define ETX_N_DEVICES {nd}")
    out.append(f"#define ETX_N_TASKS {len(plan.tasks)}")
    out.append(f"#define ETX_N_DOMAINS {ndom}")
    out.append(f"#define ETX_WORKERS_PER_DOMAIN {wpd}")
    out.append(f"#define ETX_N_WORKERS {nw}")
    out.append(f"#define ETX_THREADS {max([gg.resource.threads for gg in g.grids] + [64])}")
    out.append(_arr("etx_n_tasks_dev", [sum(1 for t in plan.tasks if t.device == d) for d in range(nd)]))
    # descriptors (global ids)
    descs = []
    for t in plan.tasks:
        c = list(t.coord) + [0] * (4 - len(t.coord))
        descs.append(f"{{{t.type_id}, {{{c[0]}, {c[1]}, {c[2]}, {c[3]}}}}}")
    out.append(f"static const etx_task etx_descs[ETX_N_TASKS] = {{{', '.join(descs)}}};")
    # static queues, all devices concatenated; begin/end indexed by dev*ETX_N_WORKERS + w
    sq, begin, end = [], [], []
    for d in range(nd):
        for w in range(nw):
            q = plan.static_queues.get((d, w), [])
            begin.append(len(sq)); sq.extend(q); end.append(len(sq))
    out.append(f"#define ETX_STATIC_LEN {max(1, len(sq))}")
    out.append(_arr("etx_static_queue", sq, dims="ETX_STATIC_LEN"))
    out.append(_arr("etx_static_begin", begin, dims="ETX_N_DEVICES * ETX_N_WORKERS"))
    out.append(_arr("etx_static_end", end, dims="ETX_N_DEVICES * ETX_N_WORKERS"))
    # events (one shared buffer)
    evs = list(plan.events.values())
    out.append(f"#define ETX_N_EVENTS {len(evs)}")
    total_words = sum(e.numel for e in evs)
    out.append(f"#define ETX_EVENT_WORDS {max(1, total_words)}")
    out.append(f"#define ETX_EVENTS_FINE_GRAINED {int(any(e.memory == 'fine_grained' or e.scope == Scope.SYSTEM for e in evs))}")
    out.append(_arr("etx_ev_offset", [e.offset for e in evs]))
    shapes = []
    for e in evs:
        s = list(e.shape) + [0] * (4 - len(e.shape))
        shapes.append(f"{{{s[0]}, {s[1]}, {s[2]}, {s[3]}}}")
    out.append(f"static const int32_t etx_ev_shape[{max(1, len(evs))}][4] = {{{', '.join(shapes) or '{0,0,0,0}'}}};")
    counts: list[int] = []
    for e in evs:
        counts.extend(e.counts)
    out.append(_arr("etx_ev_counts", counts, dims="ETX_EVENT_WORDS"))
    out.append(_arr("etx_ev_runtime_init", [1 if e.runtime_init else 0 for e in evs]))
    # queues per device
    out.append(_arr("etx_local_capacity", [plan.local_queue_capacity.get((d, dom), 0) for d in range(nd) for dom in range(ndom)],
                    dims="ETX_N_DEVICES * ETX_N_DOMAINS"))
    out.append(_arr("etx_global_capacity", [plan.global_queue_capacity.get(d, 0) for d in range(nd)], dims="ETX_N_DEVICES"))
    # push lists CSR: hybrid -> (domain << 24) | task ; dynamic -> ~task
    push_index, offsets, lists = [], [], []
    for e in evs:
        push_index.append(len(offsets))
        for lin in range(e.numel):
            offsets.append(len(lists))
            for tid in dict.fromkeys(plan.ev_consumers.get((e.name, lin), [])):
                t = plan.tasks[tid]
                lists.append(((t.domain << 24) | tid) if t.mode == "hybrid" else ~tid)
        offsets.append(len(lists))
    out.append(_arr("etx_push_index", push_index))
    out.append(_arr("etx_push_offsets", offsets))
    out.append(_arr("etx_push_lists", lists))
    # remaining-dependency counters and initial ready lists per device
    remaining: list[int] = []
    init_local: list[list[int]] = [[] for _ in range(nd * ndom)]
    init_global: list[list[int]] = [[] for _ in range(nd)]
    for t in plan.tasks:
        n_in = len(set(inst.task_in[(t.grid, t.coord)]))
        remaining.append(n_in if t.mode != "static" else 0)
        if t.mode != "static" and n_in == 0:
            (init_local[t.device * ndom + t.domain] if t.mode == "hybrid" else init_global[t.device]).append(t.id)
    out.append(_arr("etx_task_remaining", remaining, dims="ETX_N_TASKS"))
    flat_local = [tid for lst in init_local for tid in lst]
    out.append(_arr("etx_init_local", flat_local))
    out.append(_arr("etx_init_local_len", [len(lst) for lst in init_local], dims="ETX_N_DEVICES * ETX_N_DOMAINS"))
    flat_global = [tid for lst in init_global for tid in lst]
    out.append(_arr("etx_init_global", flat_global))
    out.append(_arr("etx_init_global_len", [len(lst) for lst in init_global], dims="ETX_N_DEVICES"))
    # tensors
    names = [n for n, _ in sorted(args.items(), key=lambda kv: kv[1])]
    out.append(f"#define ETX_N_ARGS {len(names)}")
    out.append("static const char* const etx_arg_names[ETX_N_ARGS] = {" + ", ".join(f'"{n}"' for n in names) + "};")
    out.append("static const size_t etx_arg_bytes[ETX_N_ARGS] = {" + ", ".join(str(g.tensors[n].nbytes(plan.bindings)) for n in names) + "};")
    out.append("static const int32_t etx_arg_role[ETX_N_ARGS] = {" + ", ".join(str(ROLE_ID.get(g.tensors[n].role, 0)) for n in names) + "};")
    # which device writes each tensor (-1 = none / input): the host's allocation policy
    writer_dev = []
    for n in names:
        ws = [gg.device for gg in g.grids if n in gg.writes]
        writer_dev.append(ws[0] if ws else -1)
    out.append("static const int32_t etx_arg_writer_device[ETX_N_ARGS] = {" + ", ".join(map(str, writer_dev)) + "};")
    # per task type: global arg indices in the grid's own argument order (-1 = unused slot)
    n_types = len(plan.type_ids)
    all_grids = list(g.grids) + list(plan.inlined.values())
    max_args = max([len(gg.args) for gg in all_grids] + [1])
    by_type = {plan.type_ids[gg.name]: gg for gg in all_grids}
    rows = []
    for t in range(n_types):
        gg = by_type.get(t)
        idx = [args[a] for a in gg.args] if gg else []
        idx += [-1] * (max_args - len(idx))
        rows.append("{" + ", ".join(map(str, idx)) + "}")
    out.append(f"#define ETX_N_TYPES {n_types}")
    out.append(f"#define ETX_MAX_ARGS {max_args}")
    out.append(f"static const int32_t etx_type_arg_index[ETX_N_TYPES][ETX_MAX_ARGS] = {{{', '.join(rows)}}};")
    out.append("")
    return "\n".join(out)
