"""ETX tiles for imported kernels: one link-mode tile per import (etx_tile_<export>).

The thread index is passed through a volatile asm: everything a kernel derives from its thread id alone is
invariant in the persistent loop, and without the barrier LLVM hoists those values out of every inlined
tile into the loop preheader, where they stay live together (measured: 38 VGPR spills with the Qwen3-8B
tile set, 0 per tile alone).

A task of an imported grid runs `slots` of the kernel's original blocks side by side: slot s of task t is
block t * slots + s. The kernel's argument block for this grid instance is at byte c->cst[0] of the grid's
first argument (one buffer holds the blocks of every instance; etx.importer.argblock lays them out), and
ends with u32 grid[3], u32 nblocks. Waves beyond the last slot and slots past the last block do nothing.
"""
from __future__ import annotations


def emit_adapters(imports: dict) -> str:
    lds = max([i["lds_bytes"] for i in imports.values()] + [16])
    out = ["// generated by etx.importer.adapter: ETX tiles for kernels imported at the IR level", "#pragma once",
           "#define ETX_HAS_IMPORTS 1", f"#define ETX_IMPORT_LDS {lds}",
           f"#define ETX_IMPORT_SLOTS {max([i['slots'] for i in imports.values()] + [1])}   // one set of slot-barrier words per slot",
           '#include "etx/abi.h"', '#include "etx/import.h"', ""]
    for e, i in imports.items():
        st, k, g = i["slot_threads"], i["slots"], i["grid_offset"]
        out += [f"// {i.get('spec', i['kernel'])}  block {tuple(i['block'])}, {k} slot(s) of {st} threads, {i['lds_bytes']} B LDS",
                f'extern "C" __device__ void etx_imp_{e}(const void* args, int blk, int tid, int slot);',
                f'extern "C" __device__ __attribute__((always_inline)) void etx_tile_{e}(const etx_ctx* c) {{',
                "  int tx; asm volatile(\"v_mov_b32 %0, %1\" : \"=v\"(tx) : \"v\"((int)threadIdx.x));   // opaque per task: see below",
                f"  const int slot = tx / {st}, tid = tx - slot * {st};",
                f"  if (slot >= {k}) return;",
                "  const unsigned char* a = (const unsigned char*)c->args[0] + c->cst[0];",
                f"  const int nblk = *(const int*)(a + {g + 12});",
                f"  const int blk = c->coord[0] * {k} + slot;",
                f"  if (blk < nblk) etx_imp_{e}(a, blk, tid, slot);",
                "}", ""]
    return "\n".join(out)


def ntasks(info: dict, grid: tuple[int, int, int]) -> int:
    n = grid[0] * grid[1] * grid[2]
    return (n + info["slots"] - 1) // info["slots"]


_TY = {"i1": "b", "i8": "b", "i16": "s", "i32": "i", "i64": "l", "float": "f", "double": "d", "half": "h", "bfloat": "h"}


def emit_host_header(imports: dict) -> str:
    """C++ descriptors of every import's argument block, for the host (offsets and a type code per parameter:
    p pointer, i i32, l i64, f float, d double, b bool/i8, s i16, h 16-bit float)."""
    out = ["// generated by etx.importer.adapter: argument-block layouts of the imported kernels", "#pragma once",
           "struct etx_imp_desc { const char* name; int nparams; int arg_bytes; int grid_off; int off[32]; char ty[33]; int block[3]; };", ""]
    for e, i in imports.items():
        ps = i["params"]
        if len(ps) > 32:
            raise ValueError(f"{e}: more than 32 parameters")
        offs = ", ".join(str(p["offset"]) for p in ps) or "0"
        tys = "".join("p" if p["ty"].startswith("ptr") else _TY[p["ty"]] for p in ps)
        b = i["block"]
        out.append(f'static const etx_imp_desc etx_imp_{e}_desc = {{"{e}", {len(ps)}, {i["arg_bytes"]}, {i["grid_offset"]}, {{{offs}}}, "{tys}", {{{b[0]}, {b[1]}, {b[2]}}}}};')
    out.append("")
    out.append("static const etx_imp_desc* etx_imp_find(const char* name) {")
    for e in imports:
        out.append(f'  if (!__builtin_strcmp(name, "{e}")) return &etx_imp_{e}_desc;')
    out.append("  return nullptr;")
    out.append("}")
    return "\n".join(out) + "\n"


def main():
    import argparse
    import json
    from pathlib import Path
    ap = argparse.ArgumentParser(description="adapter tiles + host header from imports.json")
    ap.add_argument("imports"); ap.add_argument("--tiles", required=True); ap.add_argument("--header", required=True)
    a = ap.parse_args()
    imp = json.loads(Path(a.imports).read_text())
    Path(a.tiles).write_text(emit_adapters(imp))
    Path(a.header).write_text(emit_host_header(imp))


if __name__ == "__main__":
    main()
